import { Geist, Geist_Mono, Signika } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import '@/app/_components/style.css'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const signika = Signika({
  variable: "--font-signika",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${signika.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />  
      </body>
    </html>
  );
}
